/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/validate-pricing.mjs — do not edit by hand.
 * Source: docs/cloud/pricing/*.yaml
 */
export const PRICING_BUNDLE_VERSION = "1"

export const ECONOMICS = {
  "metadoc_service_fee_pct": 0.03,
  "steam_mtx_effective_fee_pct": 0.3,
  "credits_per_usd_pool": 1000
} as const

export const FIRST_PURCHASE = {
  "grant_fraction_of_list_price_usd": 0.2,
  "app_list_price_usd": 29.99
} as const

export const STEAM_MTX_ITEMS = [
  {
    "steam_item_id": "100",
    "label": "MetaDoc Cloud · Tier 100 (starter)",
    "usd_price": 0.99,
    "amount_cents_usd": 99,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "200",
    "label": "MetaDoc Cloud · Tier 200 (~10pct off vs 2x starter USD)",
    "usd_price": 1.79,
    "amount_cents_usd": 179,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "500",
    "label": "MetaDoc Cloud · Tier 500 (~19pct off vs 5x starter USD)",
    "usd_price": 3.99,
    "amount_cents_usd": 399,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "1000",
    "label": "MetaDoc Cloud · Tier 1000 (~24pct off vs 10x starter USD)",
    "usd_price": 7.49,
    "amount_cents_usd": 749,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "2000",
    "label": "MetaDoc Cloud · Tier 2000 (~29pct off vs 20x starter USD)",
    "usd_price": 13.99,
    "amount_cents_usd": 1399,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "5000",
    "label": "MetaDoc Cloud · Tier 5000 (~33pct off vs 50x starter USD)",
    "usd_price": 32.99,
    "amount_cents_usd": 3299,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "10000",
    "label": "MetaDoc Cloud · Tier 10000 (~36pct off vs 100x starter USD)",
    "usd_price": 62.99,
    "amount_cents_usd": 6299,
    "listed": true,
    "volume_bonus_credits": 0
  }
] as const

export const N1N_MODEL_RATES = {
  "version": "2026-04-16",
  "source": "https://docs.n1n.ai/llm-api-price",
  "models": [
    {
      "id": "gpt-4o-mini",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 40
    },
    {
      "id": "gpt-4o",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 120
    },
    {
      "id": "gpt-4.1-mini",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 45
    },
    {
      "id": "gpt-4.1",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 130
    },
    {
      "id": "gpt-4.1-nano",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 25
    },
    {
      "id": "o4-mini",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 55
    },
    {
      "id": "o3-mini",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 50
    },
    {
      "id": "deepseek-chat",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 35
    },
    {
      "id": "deepseek-reasoner",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 90
    },
    {
      "id": "qwen-turbo",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 30
    },
    {
      "id": "qwen-plus",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 55
    },
    {
      "id": "qwen-max",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 100
    },
    {
      "id": "claude-3-5-sonnet-20241022",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 140
    },
    {
      "id": "claude-3-5-haiku-20241022",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 50
    },
    {
      "id": "gemini-2.0-flash",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 35
    },
    {
      "id": "gemini-2.0-flash-lite",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 22
    }
  ]
} as const
