/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/validate-pricing.mjs — do not edit by hand.
 * Source: docs/cloud/pricing/*.yaml
 */
export const PRICING_BUNDLE_VERSION = "1"

export const ECONOMICS = {
  "metadoc_service_fee_pct": 0.1,
  "steam_mtx_effective_fee_pct": 0.3,
  "credits_per_usd_pool": 1000
} as const

export const FIRST_PURCHASE = {
  "grant_fraction_of_list_price_usd": 0.2,
  "app_list_price_usd": 29.99
} as const

export const STEAM_MTX_ITEMS = [
  {
    "steam_item_id": "100",
    "label": "100 Credit Pack",
    "subtitle": "MetaDoc 100 Credit Pack",
    "description": "MetaDoc 100 Credit Pack",
    "credits_on_redeem": 100,
    "cny_price": 1,
    "usd_price": 0.23,
    "amount_cents_usd": 23,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "200",
    "label": "210 Credit Pack",
    "subtitle": "MetaDoc 210 Credit Pack",
    "description": "MetaDoc 210 Credit Pack",
    "credits_on_redeem": 210,
    "cny_price": 2,
    "usd_price": 0.45,
    "amount_cents_usd": 45,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "500",
    "label": "540 Credit Pack",
    "subtitle": "MetaDoc 540 Credit Pack",
    "description": "MetaDoc 540 Credit Pack",
    "credits_on_redeem": 540,
    "cny_price": 5,
    "usd_price": 1.11,
    "amount_cents_usd": 111,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "1000",
    "label": "1090 Credit Pack",
    "subtitle": "MetaDoc 1090 Credit Pack",
    "description": "MetaDoc 1090 Credit Pack",
    "credits_on_redeem": 1090,
    "cny_price": 10,
    "usd_price": 2.21,
    "amount_cents_usd": 221,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "2000",
    "label": "2240 Credit Pack",
    "subtitle": "MetaDoc 2240 Credit Pack",
    "description": "MetaDoc 2240 Credit Pack",
    "credits_on_redeem": 2240,
    "cny_price": 20,
    "usd_price": 4.41,
    "amount_cents_usd": 441,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "5000",
    "label": "5900 Credit Pack",
    "subtitle": "MetaDoc 5900 Credit Pack",
    "description": "MetaDoc 5900 Credit Pack",
    "credits_on_redeem": 5900,
    "cny_price": 50,
    "usd_price": 11.03,
    "amount_cents_usd": 1103,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "10000",
    "label": "12500 Credit Pack",
    "subtitle": "MetaDoc 12500 Credit Pack",
    "description": "MetaDoc 12500 Credit Pack",
    "credits_on_redeem": 12500,
    "cny_price": 100,
    "usd_price": 22.05,
    "amount_cents_usd": 2205,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "20000",
    "label": "26400 Credit Pack",
    "subtitle": "MetaDoc 26400 Credit Pack",
    "description": "MetaDoc 26400 Credit Pack",
    "credits_on_redeem": 26400,
    "cny_price": 200,
    "usd_price": 44.1,
    "amount_cents_usd": 4410,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "50000",
    "label": "70000 Credit Pack",
    "subtitle": "MetaDoc 70000 Credit Pack",
    "description": "MetaDoc 70000 Credit Pack",
    "credits_on_redeem": 70000,
    "cny_price": 500,
    "usd_price": 110.23,
    "amount_cents_usd": 11023,
    "listed": true,
    "volume_bonus_credits": 0
  },
  {
    "steam_item_id": "100000",
    "label": "150000 Credit Pack",
    "subtitle": "MetaDoc 150000 Credit Pack",
    "description": "MetaDoc 150000 Credit Pack",
    "credits_on_redeem": 150000,
    "cny_price": 1000,
    "usd_price": 220.46,
    "amount_cents_usd": 22046,
    "listed": true,
    "volume_bonus_credits": 0
  }
] as const

export const N1N_MODEL_RATES = {
  "version": "2026-04-16",
  "source": "https://docs.n1n.ai/llm-api-price",
  "models": [
    {
      "id": "gpt-4o-mini",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 40
    },
    {
      "id": "gpt-4o",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 120
    },
    {
      "id": "gpt-4.1-mini",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 45
    },
    {
      "id": "gpt-4.1",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 130
    },
    {
      "id": "gpt-4.1-nano",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 25
    },
    {
      "id": "o4-mini",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 55
    },
    {
      "id": "o3-mini",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 50
    },
    {
      "id": "deepseek-chat",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 35
    },
    {
      "id": "deepseek-reasoner",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 90
    },
    {
      "id": "qwen-turbo",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 30
    },
    {
      "id": "qwen-plus",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 55
    },
    {
      "id": "qwen-max",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 100
    },
    {
      "id": "claude-3-5-sonnet-20241022",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 140
    },
    {
      "id": "claude-3-5-haiku-20241022",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 50
    },
    {
      "id": "gemini-2.0-flash",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 35
    },
    {
      "id": "gemini-2.0-flash-lite",
      "official_rate_multiplier": 1,
      "credits_per_1k_tokens_est": 22
    }
  ]
} as const
