#!/usr/bin/env python3
import subprocess
from pathlib import Path

SCRIPT = Path("scripts/update_language_key.py")

TRANSLATIONS = {
    "en_us": {
        "outline.positiveInteger": "Please enter a positive integer",
        "outline.headerLevelRequired": "Please select a header level",
        "outline.noHeadersFound": "No headers found",
        "outline.generating": "Generating outline...",
        "outline.generateFailed": "Failed to generate outline",
        "outline.regenerate": "Regenerate Outline",
        "outline.generate": "Generate Outline",
        "outline.expandAll": "Expand All",
        "outline.collapseAll": "Collapse All",
        "outline.refresh": "Refresh",
        "outline.openInNewTab": "Open in New Tab",
        "outline.addToArticle": "Add to Article",
        "outline.replaceArticle": "Replace Article",
        "outline.generateWithAI": "Generate Outline with AI",
        "outline.stopGeneration": "Stop Generation",
        "outline.noContentToGenerate": "No content to generate",
        "outline.loadFailed": "Failed to load outline",
        "outline.loaded": "Outline loaded",
        "outline.newOutline": "New Outline",
        "outline.import": "Import",
        "outline.export": "Export",
        "outline.autoSync": "Auto Sync",
        "outline.syncing": "Syncing outline...",
        "outline.saveSuccess": "Outline saved successfully",
        "outline.saveFailed": "Failed to save outline",
        "outlineTab.title": "Outline",
        "proofreadTab.acceptAll": "Accept All",
        "proofreadTab.rejectAll": "Reject All",
        "proofreadTab.accept": "Accept",
        "proofreadTab.reject": "Reject",
        "proofreadTab.processing": "Processing...",
        "proofreadTab.noSuggestions": "No suggestions",
        "proofreadTab.loadFailed": "Failed to load proofreading results",
        "proofreadTab.applyFailed": "Failed to apply changes",
        "proofreadTab.aiProofread": "AI Proofread",
        "proofreadTab.proofreading": "Proofreading...",
        "proofreadTab.complete": "Proofreading complete",
        "proofreadTab.noContent": "No content to proofread",
        "proofreadTab.selectContentFirst": "Please select content first",
        "proofreadTab.startProofread": "Start Proofreading",
        "proofreadTab.stopProofread": "Stop",
        "proofreadTab.settings": "Proofreading Settings",
        "proofreadTab.noContentFound": "No content found",
        "proofreadTab.errorAnalyzing": "Error analyzing content",
    },
    "de_DE": {
        "export.options.normalFontFamily.label": "Fließtext-Schriftart",
        "export.options.normalFontFamily.description": "Für Fließtext verwendete Schriftart",
        "export.options.normalFontSize.label": "Fließtext-Schriftgröße (pt)",
        "export.options.normalFontSize.description": "Fließtext-Schriftgröße, Einheit: Punkt (pt)",
        "export.options.normalLineHeight.label": "Fließtext-Zeilenabstand",
        "export.options.normalLineHeight.description": "Fließtext-Zeilenabstand-Multiplikator",
        "export.options.heading1FontFamily.label": "Überschrift 1 Schriftart",
        "export.options.heading1FontFamily.description": "Für Überschrift 1 verwendete Schriftart",
        "export.options.heading1FontSize.label": "Überschrift 1 Schriftgröße (pt)",
        "export.options.heading1FontSize.description": "Überschrift 1 Schriftgröße, Einheit: Punkt (pt)",
        "export.options.heading1LineHeight.label": "Überschrift 1 Zeilenabstand",
        "export.options.heading1LineHeight.description": "Überschrift 1 Zeilenabstand-Multiplikator",
        "export.options.heading2FontFamily.label": "Überschrift 2 Schriftart",
        "export.options.heading2FontFamily.description": "Für Überschrift 2 verwendete Schriftart",
        "export.options.heading2FontSize.label": "Überschrift 2 Schriftgröße (pt)",
        "export.options.heading2FontSize.description": "Überschrift 2 Schriftgröße, Einheit: Punkt (pt)",
        "export.options.heading2LineHeight.label": "Überschrift 2 Zeilenabstand",
        "export.options.heading2LineHeight.description": "Überschrift 2 Zeilenabstand-Multiplikator",
        "export.options.heading3FontFamily.label": "Überschrift 3 Schriftart",
        "export.options.heading3FontFamily.description": "Für Überschrift 3 verwendete Schriftart",
        "export.options.heading3FontSize.label": "Überschrift 3 Schriftgröße (pt)",
        "export.options.heading3FontSize.description": "Überschrift 3 Schriftgröße, Einheit: Punkt (pt)",
        "export.options.heading3LineHeight.label": "Überschrift 3 Zeilenabstand",
        "export.options.heading3LineHeight.description": "Überschrift 3 Zeilenabstand-Multiplikator",
        "export.options.heading4FontFamily.label": "Überschrift 4 Schriftart",
        "export.options.heading4FontFamily.description": "Für Überschrift 4 verwendete Schriftart",
        "export.options.heading4FontSize.label": "Überschrift 4 Schriftgröße (pt)",
        "export.options.heading4FontSize.description": "Überschrift 4 Schriftgröße, Einheit: Punkt (pt)",
        "export.options.heading4LineHeight.label": "Überschrift 4 Zeilenabstand",
        "export.options.heading4LineHeight.description": "Überschrift 4 Zeilenabstand-Multiplikator",
        "export.options.inlineStyles.label": "Inline-CSS",
        "export.options.inlineStyles.description": "CSS-Stile in HTML einbetten",
        "export.options.imageProcessing.base64": "Base64-Einbettung",
        "export.options.includeMetadata.label": "Metadaten einbeziehen",
        "export.options.includeMetadata.description": "Dokumentenmetadaten in exportiertes Markdown einbeziehen",
        "export.options.generateToc.title": "Inhaltsverzeichnis",
        "fomulaRecognition.copyFailed": "Kopieren fehlgeschlagen",
        "fomulaRecognition.deleteFailed": "Löschen fehlgeschlagen",
        "fomulaRecognition.failedCreate": "Sitzungserstellung fehlgeschlagen",
        "fomulaRecognition.failedLoading": "Sitzungslistenladen fehlgeschlagen",
        "fomulaRecognition.failedLoading1": "Sitzungsladen fehlgeschlagen",
        "fomulaRecognition.recognize": "Formelerkennungsbeispiel",
        "fomulaRecognition.renameFailed": "Umbenennung fehlgeschlagen",
        "fomulaRecognition.text": "Kopie",
        "formulaRecognition.defaultTitle": "Neue Formelerkennungssitzung",
        "formulaRecognition.newSession": "Neue Sitzung",
        "formulaRecognition.noSessionSelected": "Bitte wählen Sie eine Sitzung aus oder erstellen Sie eine neue",
        "formulaRecognition.renamePlaceholder": "Sitzungsnamen eingeben",
        "formulaRecognition.renameTitle": "Sitzung umbenennen",
        "formulaRecognition.sessionsTitle": "Formelerkennungssitzungen",
    },
    "fr_FR": {
        "export.adapters.mdToTex.name": "Markdown vers LaTeX",
        "export.adapters.mdToTex.description": "Exporter les documents Markdown au format LaTeX",
        "export.adapters.texToPdf.name": "LaTeX vers PDF",
        "export.adapters.texToPdf.description": "Compiler les documents LaTeX au format PDF",
        "export.adapters.texToTex.name": "LaTeX vers LaTeX",
        "export.adapters.texToTex.description": "Exporter les documents LaTeX",
        "export.options.pageSize.label": "Taille de page",
        "export.options.pageSize.description": "Sélectionner la taille de page PDF",
        "export.options.pageSize.descriptionTex": "Sélectionner la taille de page PDF (doit être configurée dans la classe de document LaTeX)",
        "export.options.pageSize.a4": "A4",
        "export.options.pageSize.a3": "A3",
        "export.options.pageSize.a5": "A5",
        "export.options.pageSize.b5": "B5",
        "export.options.pageSize.letter": "Letter",
        "export.options.pageSize.legal": "Legal",
        "export.options.margins.label": "Marges",
        "export.options.margins.description": "Paramètres des marges PDF",
        "export.options.margins.descriptionTex": "Paramètres des marges PDF (Note : les marges LaTeX doivent être configurées dans le document)",
        "export.options.marginTop.label": "Marge supérieure (pouces)",
        "export.options.marginTop.description": "Marge supérieure PDF, unité : pouces",
        "export.options.marginTop.descriptionTex": "Marge supérieure PDF, unité : pouces (Note : les marges LaTeX doivent être configurées dans le document)",
        "export.options.marginBottom.label": "Marge inférieure (pouces)",
        "export.options.marginBottom.description": "Marge inférieure PDF, unité : pouces",
        "export.options.marginLeft.label": "Marge gauche (pouces)",
        "export.options.marginLeft.description": "Marge gauche PDF, unité : pouces",
        "export.options.marginRight.label": "Marge droite (pouces)",
        "export.options.marginRight.description": "Marge droite PDF, unité : pouces",
        "export.options.printBackground.label": "Imprimer l'arrière-plan",
        "export.options.printBackground.description": "Inclure les couleurs et images d'arrière-plan dans le PDF",
        "export.options.tabs.basic": "Paramètres de base",
        "export.options.tabs.style": "Paramètres de style",
        "export.options.chineseFont.label": "Police chinoise",
        "export.options.chineseFont.description": "Police chinoise utilisée pour l'export PDF",
        "export.options.westernFont.label": "Police occidentale",
        "export.options.westernFont.description": "Police occidentale utilisée pour l'export PDF",
        "export.options.colorMode.label": "Mode couleur",
        "export.options.colorMode.description": "Mode couleur du PDF (couleur ou niveaux de gris)",
        "export.options.colorMode.color": "Couleur",
        "export.options.colorMode.grayscale": "Niveaux de gris",
        "export.options.enableStyleMapping.label": "Activer le mappage de styles",
        "export.options.enableStyleMapping.description": "Mapper les éléments Markdown vers les styles Word",
    },
    "ja_JP": {
        "contextMenu.insertGraph": "グラフを挿入",
        "contextMenu.redo": "やり直し",
        "contextMenu.undo": "元に戻す",
        "data-analysis-tool.analyze": "データ分析",
        "data-analysis-tool.analyze1": "自動分析",
        "data-analysis-tool.analyze2": "集計分析など",
        "data-analysis-tool.analyze3": "データ分析ツール",
        "dataAnalysisWindow.text": "デフォルト値",
        "dataAnalysisWindow.text1": "現在の推測",
        "dataAnalysisWindow.text2": "選択済み",
        "dataAnalysisWindow.text3": "次の場所で",
        "dataAnalysisWindow.tooltip": "ツールチップ",
        "detailedOutlineNode.generating": "生成中",
        "detailedOutlineNode.sizeDragAdjust": "ドラッグしてサイズ調整",
        "documentService.exportFailedFailedExport": "ドキュメントのエクスポートに失敗しました",
        "documentService.failedClose": "ドキュメントを閉じるのに失敗しました",
        "documentService.failedNew": "新しいドキュメントの作成に失敗しました",
        "documentService.loadFailedFailedLoading": "ドキュメントの読み込みに失敗しました",
        "documentService.saveFailedFailedSave": "ドキュメントの保存に失敗しました",
        "dummyView.emptyDescription": "開いているドキュメントがありません",
        "export.adapters.mdToPdf.name": "MarkdownからPDF",
        "export.adapters.mdToPdf.description": "MarkdownドキュメントをPDF形式にエクスポート",
        "export.adapters.mdToDocx.name": "MarkdownからDOCX",
        "export.adapters.mdToDocx.description": "MarkdownドキュメントをDOCX形式にエクスポート",
        "export.adapters.mdToHtml.name": "MarkdownからHTML",
        "export.adapters.mdToHtml.description": "MarkdownドキュメントをHTML形式にエクスポート",
        "export.adapters.mdToMd.name": "MarkdownからMarkdown",
        "export.adapters.mdToMd.description": "Markdownドキュメントをエクスポート",
        "export.adapters.mdToTex.name": "MarkdownからLaTeX",
        "export.adapters.mdToTex.description": "MarkdownドキュメントをLaTeX形式にエクスポート",
        "export.adapters.texToPdf.name": "LaTeXからPDF",
        "export.adapters.texToPdf.description": "LaTeXドキュメントをPDF形式にコンパイル",
        "export.adapters.texToTex.name": "LaTeXからLaTeX",
        "export.adapters.texToTex.description": "LaTeXドキュメントをエクスポート",
    },
    "ko_KR": {
        "contextMenu.insertGraph": "그래프 삽입",
        "contextMenu.redo": "다시 실행",
        "contextMenu.undo": "실행 취소",
        "data-analysis-tool.analyze": "데이터 분석",
        "data-analysis-tool.analyze1": "자동 분석",
        "data-analysis-tool.analyze2": "집계 분석 등",
        "data-analysis-tool.analyze3": "데이터 분석 도구",
        "dataAnalysisWindow.preview": "데이터 미리보기",
        "dataAnalysisWindow.text": "기본값",
        "dataAnalysisWindow.text1": "현재 추측",
        "dataAnalysisWindow.text2": "선택됨",
        "dataAnalysisWindow.text3": "다음에서",
        "dataAnalysisWindow.tooltip": "툴팁",
        "detailedOutlineNode.generating": "생성 중",
        "detailedOutlineNode.sizeDragAdjust": "드래그하여 크기 조정",
        "documentService.exportFailedFailedExport": "문서 날짜 실패",
        "documentService.failedClose": "문서 닫기 실패",
        "documentService.failedNew": "새 문서 만들기 실패",
        "documentService.loadFailedFailedLoading": "문서 불러오기 실패",
        "documentService.saveFailedFailedSave": "문서 저장 실패",
        "dummyView.emptyDescription": "열린 문서 없음",
        "export.adapters.mdToPdf.name": "Markdown에서 PDF로",
        "export.adapters.mdToPdf.description": "Markdown 문서를 PDF 형식으로 날짜",
        "export.adapters.mdToDocx.name": "Markdown에서 DOCX로",
        "export.adapters.mdToDocx.description": "Markdown 문서를 DOCX 형식으로 날짜",
        "export.adapters.mdToHtml.name": "Markdown에서 HTML로",
        "export.adapters.mdToHtml.description": "Markdown 문서를 HTML 형식으로 날짜",
        "export.adapters.mdToMd.name": "Markdown에서 Markdown으로",
        "export.adapters.mdToMd.description": "Markdown 문서 날짜",
        "export.adapters.mdToTex.name": "Markdown에서 LaTeX로",
        "export.adapters.mdToTex.description": "Markdown 문서를 LaTeX 형식으로 날짜",
        "export.adapters.texToPdf.name": "LaTeX에서 PDF로",
        "export.adapters.texToPdf.description": "LaTeX 문서를 PDF 형식으로 컴파일",
        "export.adapters.texToTex.name": "LaTeX에서 LaTeX로",
        "export.adapters.texToTex.description": "LaTeX 문서 날짜",
        "export.options.pageSize.label": "페이지 크기",
        "export.options.pageSize.description": "PDF 페이지 크기 선택",
        "export.options.pageSize.descriptionTex": "PDF 페이지 크기 선택(LaTeX 문서 클래스에서 구성 필요)",
        "export.options.pageSize.a4": "A4",
        "export.options.pageSize.a3": "A3",
        "export.options.pageSize.a5": "A5",
        "export.options.pageSize.b5": "B5",
        "export.options.pageSize.letter": "Letter",
        "export.options.pageSize.legal": "Legal",
        "export.options.margins.label": "여백",
        "export.options.margins.description": "PDF 여백 설정",
        "export.options.margins.descriptionTex": "PDF 여백 설정(참고: LaTeX 여백은 문서에서 구성해야 함)",
        "export.options.marginTop.label": "상단 여백(인치)",
        "export.options.marginTop.description": "PDF 상단 여백, 단위: 인치",
        "export.options.marginTop.descriptionTex": "PDF 상단 여백, 단위: 인치(참고: LaTeX 여백은 문서에서 구성해야 함)",
        "export.options.marginBottom.label": "하단 여백(인치)",
        "export.options.marginBottom.description": "PDF 하단 여백, 단위: 인치",
        "export.options.marginLeft.label": "왼쪽 여백(인치)",
        "export.options.marginLeft.description": "PDF 왼쪽 여백, 단위: 인치",
        "export.options.marginRight.label": "오른쪽 여백(인치)",
        "export.options.marginRight.description": "PDF 오른쪽 여백, 단위: 인치",
        "export.options.printBackground.label": "배경 인쇄",
        "export.options.printBackground.description": "PDF에 배경 색상과 이미지 포함",
        "export.options.tabs.basic": "기본 설정",
        "export.options.tabs.style": "스타일 설정",
        "export.options.chineseFont.label": "중국어 글꼴",
        "export.options.chineseFont.description": "PDF 날짜에 사용되는 중국어 글꼴",
        "export.options.westernFont.label": "서양어 글꼴",
        "export.options.westernFont.description": "PDF 날짜에 사용되는 서양어 글꼴",
        "export.options.colorMode.label": "색상 모드",
        "export.options.colorMode.description": "PDF 색상 모드(컬러 또는 흑백)",
        "export.options.colorMode.color": "컬러",
        "export.options.colorMode.grayscale": "흑백",
        "export.options.enableStyleMapping.label": "스타일 매핑 활성화",
        "export.options.enableStyleMapping.description": "Markdown 요소를 Word 스타일에 매핑",
    },
}


def update_key(lang, key, value):
    cmd = [
        "python",
        str(SCRIPT),
        "--lang",
        lang,
        "--key",
        key,
        "--value",
        value,
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        print(f"  ✅ {key}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"  ❌ {key}: {e.stderr}")
        return False


def main():
    print("=" * 70)
    print("Batch Translation Processing - Batch 5")
    print("=" * 70)
    print()

    total_updated = 0

    for lang, translations in TRANSLATIONS.items():
        print(f"\n🌐 Processing {lang}...")
        print("-" * 70)

        updated = 0
        for key, value in translations.items():
            if update_key(lang, key, value):
                updated += 1

        print(f"  Updated {updated}/{len(translations)} keys")
        total_updated += updated

    print()
    print("=" * 70)
    print(f"Total keys updated: {total_updated}")
    print("=" * 70)


if __name__ == "__main__":
    main()
