/**
 * 校验 docs/cloud/pricing/*.yaml 并生成 cloudflare-worker/src/pricing-generated.ts
 * Usage: node scripts/validate-pricing.mjs
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { parse as parseYaml } from 'yaml'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')
const pricingDir = path.join(root, 'docs', 'cloud', 'pricing')
const outTs = path.join(root, 'cloudflare-worker', 'src', 'pricing-generated.ts')

function load(name) {
  const p = path.join(pricingDir, name)
  const text = fs.readFileSync(p, 'utf8')
  return parseYaml(text)
}

function main() {
  const economics = load('economics.yaml')
  const items = load('steam-mtx-items.yaml')
  const n1n = load('n1n-model-rates.yaml')

  if (!economics.economics) throw new Error('economics.yaml: missing economics')
  const e = economics.economics
  const keys = ['metadoc_service_fee_pct', 'steam_mtx_effective_fee_pct', 'credits_per_usd_pool']
  for (const k of keys) {
    if (e[k] === undefined) throw new Error(`economics.yaml: missing ${k}`)
  }
  if (e.metadoc_service_fee_pct < 0 || e.metadoc_service_fee_pct > 1) {
    throw new Error('metadoc_service_fee_pct out of range')
  }

  if (!Array.isArray(items.items) || items.items.length === 0) {
    throw new Error('steam-mtx-items.yaml: items required')
  }
  const seen = new Set()
  for (const it of items.items) {
    if (!it.steam_item_id || seen.has(String(it.steam_item_id))) {
      throw new Error(`duplicate or missing steam_item_id: ${it.steam_item_id}`)
    }
    seen.add(String(it.steam_item_id))
    if (typeof it.usd_price !== 'number' || typeof it.amount_cents_usd !== 'number') {
      throw new Error(`invalid price for item ${it.steam_item_id}`)
    }
    const expectedCents = Math.round(it.usd_price * 100)
    if (it.amount_cents_usd !== expectedCents) {
      throw new Error(
        `steam-mtx-items.yaml: item ${it.steam_item_id} amount_cents_usd (${it.amount_cents_usd}) must equal Math.round(usd_price*100)=${expectedCents}`
      )
    }
    if (it.volume_bonus_credits !== undefined) {
      const b = it.volume_bonus_credits
      if (!Number.isInteger(b) || b < 0) {
        throw new Error(`invalid volume_bonus_credits for item ${it.steam_item_id}`)
      }
    }
  }

  if (!Array.isArray(n1n.models) || n1n.models.length === 0) {
    throw new Error('n1n-model-rates.yaml: models required')
  }

  const fp = economics.first_purchase
  if (!fp || typeof fp.grant_fraction_of_list_price_usd !== 'number') {
    throw new Error('economics.yaml: first_purchase.grant_fraction_of_list_price_usd required')
  }
  if (typeof fp.app_list_price_usd !== 'number' || fp.app_list_price_usd <= 0) {
    throw new Error('economics.yaml: first_purchase.app_list_price_usd must be a positive number')
  }

  const ts = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/validate-pricing.mjs — do not edit by hand.
 * Source: docs/cloud/pricing/*.yaml
 */
export const PRICING_BUNDLE_VERSION = ${JSON.stringify(String(economics.version || '1'))}

export const ECONOMICS = ${JSON.stringify(e, null, 2)} as const

export const FIRST_PURCHASE = ${JSON.stringify(fp, null, 2)} as const

export const STEAM_MTX_ITEMS = ${JSON.stringify(items.items, null, 2)} as const

export const N1N_MODEL_RATES = ${JSON.stringify(n1n, null, 2)} as const
`

  fs.writeFileSync(outTs, ts, 'utf8')
  console.log('OK: wrote', path.relative(root, outTs))
}

main()
