import type { DocumentTemplate } from '../types/formats'

/**
 * Markdown 模板
 */
export const markdownTemplates: Record<string, DocumentTemplate> = {
  blank: {
    id: 'blank',
    label: '空白文档',
    labelKey: 'newDocument.templates.markdown.blank.label',
    description: '创建一个空白的 Markdown 文档',
    descriptionKey: 'newDocument.templates.markdown.blank.description',
    content: ''
  },
  article: {
    id: 'article',
    label: '文章模板',
    labelKey: 'newDocument.templates.markdown.article.label',
    description: '包含基本结构的文章模板',
    descriptionKey: 'newDocument.templates.markdown.article.description',
    content: [
      '# 标题',
      '',
      '## 摘要',
      '',
      '在这里撰写摘要内容。',
      '',
      '## 正文',
      '',
      '- 要点一',
      '- 要点二',
      '',
      '## 结论',
      '',
      '在这里撰写结论内容。',
      ''
    ].join('\n')
  }
}

/**
 * LaTeX 模板
 */
export const latexTemplates: Record<string, DocumentTemplate> = {
  article: {
    id: 'article',
    label: '标准文章',
    labelKey: 'newDocument.templates.latex.article.label',
    description: '包含基础结构的 LaTeX 文章模板',
    descriptionKey: 'newDocument.templates.latex.article.description',
    content: [
      '\\documentclass{article}',
      '\\usepackage{fontspec}',
      '\\usepackage{xeCJK}',
      '\\usepackage{graphicx}',
      '\\usepackage{hyperref}',
      '\\usepackage{amsmath}',
      '\\usepackage{amssymb}',
      '\\usepackage{ulem}',
      '\\usepackage{geometry}',
      '\\usepackage{color}',
      '\\usepackage{fancyhdr}',
      '\\usepackage{lastpage}',
      '',
      '% 英文正文字体',
      '\\setmainfont{Times New Roman}',
      '\\setsansfont{Arial}',
      '\\setmonofont{Consolas}',
      '',
      '% 中文字体',
      '\\setCJKmainfont{SimSun}',
      '\\setCJKsansfont{Microsoft YaHei}',
      '\\setCJKmonofont{FangSong}',
      '',
      '\\title{未命名文档}',
      '\\author{}',
      '\\date{\\today}',
      '',
      '\\begin{document}',
      '\\maketitle',
      '',
      '\\section{引言}',
      '请在此处撰写引言内容。',
      '',
      '\\section{主体}',
      '请在此处撰写主体内容。',
      '',
      '\\section{结论}',
      '请在此处撰写结论内容。',
      '',
      '\\end{document}',
      ''
    ].join('\n')
  },
  report: {
    id: 'report',
    label: '报告模板',
    labelKey: 'newDocument.templates.latex.report.label',
    description: '适用于学术报告的模板',
    descriptionKey: 'newDocument.templates.latex.report.description',
    content: [
      '\\documentclass{report}',
      '\\usepackage{fontspec}',
      '\\usepackage{xeCJK}',
      '\\usepackage{graphicx}',
      '\\usepackage{hyperref}',
      '\\usepackage{amsmath}',
      '\\usepackage{amssymb}',
      '\\usepackage{ulem}',
      '\\usepackage{geometry}',
      '\\usepackage{color}',
      '\\usepackage{fancyhdr}',
      '\\usepackage{lastpage}',
      '',
      '% 英文正文字体',
      '\\setmainfont{Times New Roman}',
      '\\setsansfont{Arial}',
      '\\setmonofont{Consolas}',
      '',
      '% 中文字体',
      '\\setCJKmainfont{SimSun}',
      '\\setCJKsansfont{Microsoft YaHei}',
      '\\setCJKmonofont{FangSong}',
      '',
      '\\title{报告标题}',
      '\\author{}',
      '\\date{\\today}',
      '',
      '\\begin{document}',
      '\\maketitle',
      '',
      '\\chapter{引言}',
      '请在此处撰写引言内容。',
      '',
      '\\chapter{内容}',
      '请在此处撰写正文内容。',
      '',
      '\\chapter{结论}',
      '请在此处撰写结论内容。',
      '',
      '\\end{document}',
      ''
    ].join('\n')
  },
  // 中文国标学术论文（单栏）
  gb7714_zh: {
    id: 'gb7714_zh',
    label: '中文国标学术论文',
    labelKey: 'newDocument.templates.latex.gb7714_zh.label',
    description: '符合 GB/T 7714-2015 标准的中文学术论文模板',
    descriptionKey: 'newDocument.templates.latex.gb7714_zh.description',
    content: [
      '\\documentclass[12pt,a4paper]{article}',
      '\\usepackage[UTF8]{ctex}',
      '\\usepackage{fontspec}',
      '\\usepackage{geometry}',
      '\\geometry{left=2.5cm,right=2.5cm,top=3cm,bottom=2.5cm}',
      '\\usepackage{amsmath,amssymb,amsfonts}',
      '\\usepackage{graphicx}',
      '\\usepackage{booktabs}',
      '\\usepackage{multirow}',
      '\\usepackage{hyperref}',
      '\\usepackage{cite}',
      '\\usepackage{setspace}',
      '\\onehalfspacing',
      '',
      '% 字体设置',
      '\\setmainfont{Times New Roman}  % 英文正文字体',
      '\\setsansfont{Microsoft YaHei}  % 雅黑（可选）',
      '\\setmonofont{Consolas}',
      '\\setCJKmainfont{SimSun}        % 宋体',
      '\\setCJKsansfont{Microsoft YaHei}',
      '',
      '% 标题信息',
      '\\title{论文标题}',
      '\\author{作者姓名}',
      '\\date{\\today}',
      '',
      '\\begin{document}',
      '',
      '% 标题页',
      '\\maketitle',
      '',
      '% 摘要',
      '\\begin{abstract}',
      '\\textbf{摘要：} 在此处撰写摘要内容。摘要应简洁明了地概括论文的主要内容、研究方法、主要结果和结论。',
      '',
      '\\textbf{关键词：} 关键词1；关键词2；关键词3',
      '\\end{abstract}',
      '',
      '% 目录',
      '\\tableofcontents',
      '\\newpage',
      '',
      '% 正文',
      '\\section{引言}',
      '引言部分应介绍研究背景、研究意义、国内外研究现状以及本文的研究内容和组织结构。',
      '',
      '\\section{相关工作}',
      '相关工作部分应综述与本文研究相关的已有研究成果，分析现有方法的优缺点，指出本文研究的创新点。',
      '',
      '\\section{研究方法}',
      '研究方法部分应详细描述本文所采用的研究方法、实验设计、数据来源等。',
      '',
      '\\subsection{方法概述}',
      '在此处描述方法的基本思路和框架。',
      '',
      '\\subsection{具体实现}',
      '在此处描述方法的具体实现细节。',
      '',
      '\\section{实验结果与分析}',
      '实验结果与分析部分应展示实验数据、分析结果，并对结果进行讨论。',
      '',
      '\\subsection{实验设置}',
      '在此处描述实验的环境、参数设置等。',
      '',
      '\\subsection{结果分析}',
      '在此处展示和分析实验结果。',
      '',
      '\\section{结论}',
      '结论部分应总结本文的主要贡献，指出研究的局限性，并提出未来的研究方向。',
      '',
      '% 参考文献',
      '\\begin{thebibliography}{99}',
      '\\bibitem{ref1} 参考文献1',
      '\\bibitem{ref2} 参考文献2',
      '\\end{thebibliography}',
      '',
      '% 附录（可选）',
      '\\appendix',
      '\\section{附录A}',
      '附录内容（如有需要）。',
      '',
      '\\end{document}',
      ''
    ].join('\n')
  },
  // 英文标准学术论文（单栏）
  ieee_en: {
    id: 'ieee_en',
    label: '英文标准学术论文',
    labelKey: 'newDocument.templates.latex.ieee_en.label',
    description: '符合 IEEE 标准的英文学术论文模板',
    descriptionKey: 'newDocument.templates.latex.ieee_en.description',
    content: [
      '\\documentclass[conference]{IEEEtran}',
      '\\IEEEoverridecommandlockouts',
      '\\usepackage{cite}',
      '\\usepackage{amsmath,amssymb,amsfonts}',
      '\\usepackage{algorithmic}',
      '\\usepackage{graphicx}',
      '\\usepackage{textcomp}',
      '\\usepackage{xcolor}',
      '\\def\\BibTeX{{\\rm B\\kern-.05em{\\sc i\\kern-.025em b}\\kern-.08em',
      '    T\\kern-.1667em\\lower.7ex\\hbox{E}\\kern-.125emX}}',
      '',
      '\\begin{document}',
      '',
      '% Title',
      '\\title{Your Paper Title Here\\thanks{*This work was supported by...}}',
      '',
      '\\author{\\IEEEauthorblockN{1\\textsuperscript{st} Author Name}',
      '\\IEEEauthorblockA{\\textit{Dept. of Your Department} \\\\',
      '\\textit{Your University}\\\\',
      'City, Country\\\\',
      'email@example.com}',
      '\\and',
      '\\IEEEauthorblockN{2\\textsuperscript{nd} Author Name}',
      '\\IEEEauthorblockA{\\textit{Dept. of Your Department} \\\\',
      '\\textit{Your University}\\\\',
      'City, Country\\\\',
      'email@example.com}}',
      '',
      '\\maketitle',
      '',
      '\\begin{abstract}',
      'The abstract should briefly summarize the contents of the paper in 150--250 words.',
      '\\end{abstract}',
      '',
      '\\begin{IEEEkeywords}',
      'component, formatting, style, styling, insert',
      '\\end{IEEEkeywords}',
      '',
      '\\section{Introduction}',
      'This document is a model and instructions for \\LaTeX\\. Please observe the',
      'conversion from program code to \\LaTeX\\ document. The introduction section',
      'should provide the background and motivation for the work.',
      '',
      '\\section{Related Work}',
      'This section should review the related work and position your contribution',
      'in the context of existing research.',
      '',
      '\\section{Methodology}',
      'This section should describe your methodology in detail.',
      '',
      '\\subsection{Method Overview}',
      'Describe the overall approach and framework.',
      '',
      '\\subsection{Implementation Details}',
      'Provide specific implementation details.',
      '',
      '\\section{Experimental Results}',
      'This section should present and analyze the experimental results.',
      '',
      '\\subsection{Experimental Setup}',
      'Describe the experimental environment and parameter settings.',
      '',
      '\\subsection{Results and Analysis}',
      'Present and analyze the experimental results.',
      '',
      '\\section{Conclusion}',
      'The conclusion should summarize the main contributions, discuss limitations,',
      'and suggest future research directions.',
      '',
      '\\begin{thebibliography}{00}',
      '\\bibitem{b1} G. Eason, B. Noble, and I. N. Sneddon, "On certain integrals of',
      'Lipschitz-Hankel type involving products of Bessel functions," Phil. Trans. Roy. Soc. London, vol. A247, pp. 529--551, April 1955.',
      '\\bibitem{b2} J. Clerk Maxwell, A Treatise on Electricity and Magnetism, 3rd ed., vol. 2. Oxford: Clarendon, 1892, pp.68--73.',
      '\\end{thebibliography}',
      '',
      '\\end{document}',
      ''
    ].join('\n')
  },
  // 中文国标学术论文（双栏）
  gb7714_zh_twocolumn: {
    id: 'gb7714_zh_twocolumn',
    label: '中文国标学术论文（双栏）',
    labelKey: 'newDocument.templates.latex.gb7714_zh_twocolumn.label',
    description: '符合 GB/T 7714-2015 标准的中文学术论文模板（双栏排版）',
    descriptionKey: 'newDocument.templates.latex.gb7714_zh_twocolumn.description',
    content: [
      '\\documentclass[12pt,a4paper,twocolumn]{article}',
      '\\usepackage[UTF8]{ctex}',
      '\\usepackage{fontspec}',
      '\\usepackage{geometry}',
      '\\geometry{left=1.8cm,right=1.8cm,top=2.5cm,bottom=2.5cm,columnsep=0.8cm}',
      '\\usepackage{amsmath,amssymb,amsfonts}',
      '\\usepackage{graphicx}',
      '\\usepackage{booktabs}',
      '\\usepackage{multirow}',
      '\\usepackage{hyperref}',
      '\\usepackage{cite}',
      '\\usepackage{setspace}',
      '\\onehalfspacing',
      '',
      '% 字体设置',
      '\\setmainfont{Times New Roman}  % 英文正文字体',
      '\\setsansfont{Microsoft YaHei}  % 雅黑（可选）',
      '\\setmonofont{Consolas}',
      '\\setCJKmainfont{SimSun}        % 宋体',
      '\\setCJKsansfont{Microsoft YaHei}',
      '',
      '% 标题信息',
      '\\title{论文标题}',
      '\\author{作者姓名}',
      '\\date{\\today}',
      '',
      '\\begin{document}',
      '',
      '% 标题页（单栏）',
      '\\twocolumn[',
      '\\maketitle',
      '\\begin{abstract}',
      '\\textbf{摘要：} 在此处撰写摘要内容。摘要应简洁明了地概括论文的主要内容、研究方法、主要结果和结论。',
      '',
      '\\textbf{关键词：} 关键词1；关键词2；关键词3',
      '\\end{abstract}',
      ']',
      '',
      '% 正文（双栏）',
      '\\section{引言}',
      '引言部分应介绍研究背景、研究意义、国内外研究现状以及本文的研究内容和组织结构。',
      '',
      '\\section{相关工作}',
      '相关工作部分应综述与本文研究相关的已有研究成果，分析现有方法的优缺点，指出本文研究的创新点。',
      '',
      '\\section{研究方法}',
      '研究方法部分应详细描述本文所采用的研究方法、实验设计、数据来源等。',
      '',
      '\\subsection{方法概述}',
      '在此处描述方法的基本思路和框架。',
      '',
      '\\subsection{具体实现}',
      '在此处描述方法的具体实现细节。',
      '',
      '\\section{实验结果与分析}',
      '实验结果与分析部分应展示实验数据、分析结果，并对结果进行讨论。',
      '',
      '\\subsection{实验设置}',
      '在此处描述实验的环境、参数设置等。',
      '',
      '\\subsection{结果分析}',
      '在此处展示和分析实验结果。',
      '',
      '\\section{结论}',
      '结论部分应总结本文的主要贡献，指出研究的局限性，并提出未来的研究方向。',
      '',
      '% 参考文献',
      '\\begin{thebibliography}{99}',
      '\\bibitem{ref1} 参考文献1',
      '\\bibitem{ref2} 参考文献2',
      '\\end{thebibliography}',
      '',
      '% 附录（可选）',
      '\\appendix',
      '\\section{附录A}',
      '附录内容（如有需要）。',
      '',
      '\\end{document}',
      ''
    ].join('\n')
  },
  // 英文标准学术论文（双栏）
  ieee_en_twocolumn: {
    id: 'ieee_en_twocolumn',
    label: '英文标准学术论文（双栏）',
    labelKey: 'newDocument.templates.latex.ieee_en_twocolumn.label',
    description: '符合 IEEE 标准的英文学术论文模板（双栏排版）',
    descriptionKey: 'newDocument.templates.latex.ieee_en_twocolumn.description',
    content: [
      '\\documentclass[conference,twocolumn]{IEEEtran}',
      '\\IEEEoverridecommandlockouts',
      '\\usepackage{cite}',
      '\\usepackage{amsmath,amssymb,amsfonts}',
      '\\usepackage{algorithmic}',
      '\\usepackage{graphicx}',
      '\\usepackage{textcomp}',
      '\\usepackage{xcolor}',
      '\\def\\BibTeX{{\\rm B\\kern-.05em{\\sc i\\kern-.025em b}\\kern-.08em',
      '    T\\kern-.1667em\\lower.7ex\\hbox{E}\\kern-.125emX}}',
      '',
      '\\begin{document}',
      '',
      '% Title',
      '\\title{Your Paper Title Here\\thanks{*This work was supported by...}}',
      '',
      '\\author{\\IEEEauthorblockN{1\\textsuperscript{st} Author Name}',
      '\\IEEEauthorblockA{\\textit{Dept. of Your Department} \\\\',
      '\\textit{Your University}\\\\',
      'City, Country\\\\',
      'email@example.com}',
      '\\and',
      '\\IEEEauthorblockN{2\\textsuperscript{nd} Author Name}',
      '\\IEEEauthorblockA{\\textit{Dept. of Your Department} \\\\',
      '\\textit{Your University}\\\\',
      'City, Country\\\\',
      'email@example.com}}',
      '',
      '\\maketitle',
      '',
      '\\begin{abstract}',
      'The abstract should briefly summarize the contents of the paper in 150--250 words.',
      '\\end{abstract}',
      '',
      '\\begin{IEEEkeywords}',
      'component, formatting, style, styling, insert',
      '\\end{IEEEkeywords}',
      '',
      '\\section{Introduction}',
      'This document is a model and instructions for \\LaTeX\\. Please observe the',
      'conversion from program code to \\LaTeX\\ document. The introduction section',
      'should provide the background and motivation for the work.',
      '',
      '\\section{Related Work}',
      'This section should review the related work and position your contribution',
      'in the context of existing research.',
      '',
      '\\section{Methodology}',
      'This section should describe your methodology in detail.',
      '',
      '\\subsection{Method Overview}',
      'Describe the overall approach and framework.',
      '',
      '\\subsection{Implementation Details}',
      'Provide specific implementation details.',
      '',
      '\\section{Experimental Results}',
      'This section should present and analyze the experimental results.',
      '',
      '\\subsection{Experimental Setup}',
      'Describe the experimental environment and parameter settings.',
      '',
      '\\subsection{Results and Analysis}',
      'Present and analyze the experimental results.',
      '',
      '\\section{Conclusion}',
      'The conclusion should summarize the main contributions, discuss limitations,',
      'and suggest future research directions.',
      '',
      '\\begin{thebibliography}{00}',
      '\\bibitem{b1} G. Eason, B. Noble, and I. N. Sneddon, "On certain integrals of',
      'Lipschitz-Hankel type involving products of Bessel functions," Phil. Trans. Roy. Soc. London, vol. A247, pp. 529--551, April 1955.',
      '\\bibitem{b2} J. Clerk Maxwell, A Treatise on Electricity and Magnetism, 3rd ed., vol. 2. Oxford: Clarendon, 1892, pp.68--73.',
      '\\end{thebibliography}',
      '',
      '\\end{document}',
      ''
    ].join('\n')
  }
}

/**
 * 获取指定格式的所有模板
 */
export function getTemplatesByFormat(formatId: string): DocumentTemplate[] {
  switch (formatId) {
    case 'md':
      return Object.values(markdownTemplates)
    case 'tex':
      return Object.values(latexTemplates)
    default:
      return []
  }
}

/**
 * 根据格式和模板ID获取模板
 */
export function getTemplate(formatId: string, templateId: string): DocumentTemplate | undefined {
  switch (formatId) {
    case 'md':
      return markdownTemplates[templateId]
    case 'tex':
      return latexTemplates[templateId]
    default:
      return undefined
  }
}
