/**
 * 扩展名 → Monaco / fenced-code 语言 id（无内置语言时用 plaintext，仅影响高亮与代码块标签文案）
 */
export const EXTENSION_TO_MONACO_LANGUAGE: Record<string, string> = {
  // JS / TS
  '.js': 'javascript',
  '.jsx': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  // Python / Ruby / PHP
  '.py': 'python',
  '.pyw': 'python',
  '.pyi': 'python',
  '.rb': 'ruby',
  '.rake': 'ruby',
  '.gemspec': 'ruby',
  '.php': 'php',
  '.phtml': 'php',
  // C 族
  '.c': 'c',
  '.h': 'c',
  '.i': 'c',
  '.cpp': 'cpp',
  '.cxx': 'cpp',
  '.cc': 'cpp',
  '.hpp': 'cpp',
  '.hh': 'cpp',
  '.hxx': 'cpp',
  '.inl': 'cpp',
  '.ipp': 'cpp',
  '.cu': 'cpp',
  '.cuh': 'cpp',
  // C# / Java / Kotlin / Scala
  '.cs': 'csharp',
  '.csx': 'csharp',
  '.cake': 'csharp',
  '.java': 'java',
  '.jsp': 'java',
  '.jspf': 'java',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.scala': 'scala',
  '.sc': 'scala',
  // Go / Rust / Swift / Dart
  '.go': 'go',
  '.rs': 'rust',
  '.swift': 'swift',
  '.dart': 'dart',
  // Shell / 脚本
  '.sh': 'shell',
  '.bash': 'shell',
  '.zsh': 'shell',
  '.fish': 'shell',
  '.ksh': 'shell',
  '.ps1': 'powershell',
  '.psm1': 'powershell',
  '.psd1': 'powershell',
  '.awk': 'awk',
  '.tcl': 'tcl',
  '.tk': 'tcl',
  // Web
  '.html': 'html',
  '.htm': 'html',
  '.xhtml': 'html',
  '.vue': 'html',
  '.svelte': 'html',
  '.css': 'css',
  '.scss': 'scss',
  '.sass': 'sass',
  '.less': 'less',
  // 数据交换
  '.json': 'json',
  '.jsonc': 'json',
  '.json5': 'json',
  '.xml': 'xml',
  '.xsl': 'xml',
  '.xslt': 'xml',
  '.rss': 'xml',
  '.atom': 'xml',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'toml',
  '.csv': 'csv',
  // 配置
  '.ini': 'ini',
  '.conf': 'ini',
  '.cfg': 'ini',
  '.cnf': 'ini',
  '.editorconfig': 'ini',
  '.npmrc': 'ini',
  '.properties': 'properties',
  // SQL（及常见变体后缀）
  '.sql': 'sql',
  '.ddl': 'sql',
  '.mysql': 'sql',
  '.pgsql': 'sql',
  '.sqlite': 'sql',
  '.hql': 'sql',
  // Markdown / LaTeX（.cls 多为 LaTeX 文档类；VB 的 .cls 较少出现在本工具链）
  '.md': 'markdown',
  '.markdown': 'markdown',
  '.mdown': 'markdown',
  '.tex': 'latex',
  '.ltx': 'latex',
  '.sty': 'latex',
  '.cls': 'latex',
  // R / Perl / Lua
  '.r': 'r',
  '.R': 'r',
  '.rmd': 'markdown',
  '.pl': 'perl',
  '.pm': 'perl',
  '.t': 'perl',
  '.lua': 'lua',
  '.moon': 'lua',
  // 汇编（Monaco 常无专门 id，标签仍写 asm 便于阅读）
  '.asm': 'asm',
  '.s': 'asm',
  '.S': 'asm',
  '.nasm': 'nasm',
  '.masm': 'asm',
  '.a51': 'asm',
  '.inc': 'asm',
  // .m：Objective-C 为主；Matlab 用户可用 .matlab 若需要可再扩展
  '.m': 'objective-c',
  '.mm': 'objective-c',
  // .NET / VB
  '.fs': 'fsharp',
  '.fsi': 'fsharp',
  '.fsx': 'fsharp',
  '.vb': 'vb',
  '.vbs': 'vb',
  '.bas': 'vb',
  // 函数式 / JVM 系
  '.hs': 'haskell',
  '.lhs': 'haskell',
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  '.clj': 'clojure',
  '.cljs': 'clojure',
  '.cljc': 'clojure',
  '.edn': 'clojure',
  '.erl': 'erlang',
  '.hrl': 'erlang',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.eex': 'elixir',
  '.heex': 'elixir',
  '.leex': 'elixir',
  // 构建 / 容器 / IaC
  '.gradle': 'gradle',
  '.groovy': 'groovy',
  '.gvy': 'groovy',
  '.cmake': 'cmake',
  '.dockerfile': 'dockerfile',
  '.containerfile': 'dockerfile',
  '.mk': 'makefile',
  '.mak': 'makefile',
  '.bazel': 'starlark',
  '.bzl': 'starlark',
  '.star': 'starlark',
  '.tf': 'hcl',
  '.tfvars': 'hcl',
  '.hcl': 'hcl',
  '.rego': 'rego',
  '.cue': 'cue',
  '.nix': 'nix',
  '.dhall': 'dhall',
  // GraphQL / RPC
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.proto': 'protobuf',
  '.pbtxt': 'protobuf',
  '.prisma': 'prisma',
  // 系统语言 / 新兴
  '.nim': 'nim',
  '.nims': 'nim',
  '.zig': 'zig',
  '.zon': 'zig',
  '.v': 'verilog',
  '.sv': 'systemverilog',
  '.svh': 'systemverilog',
  '.vhdl': 'vhdl',
  '.vhd': 'vhdl',
  '.d': 'd',
  '.di': 'd',
  '.cr': 'crystal',
  '.jl': 'julia',
  '.odin': 'plaintext',
  '.vsh': 'plaintext',
  // 老语言 / 专项
  '.ada': 'ada',
  '.adb': 'ada',
  '.ads': 'ada',
  '.cob': 'cobol',
  '.cbl': 'cobol',
  '.cpy': 'cobol',
  '.f': 'fortran',
  '.f90': 'fortran',
  '.f95': 'fortran',
  '.f03': 'fortran',
  '.for': 'fortran',
  '.f77': 'fortran',
  '.pas': 'pascal',
  '.pp': 'pascal',
  // WebGPU / GPU
  '.wgsl': 'wgsl',
  '.hlsl': 'hlsl',
  '.glsl': 'glsl',
  '.vert': 'glsl',
  '.frag': 'glsl',
  '.geom': 'glsl',
  '.comp': 'glsl',
  '.metal': 'metal',
  // Wasm 文本
  '.wasm': 'wasm',
  '.wat': 'wat',
  // 合约 / 链
  '.sol': 'solidity',
  '.move': 'plaintext',
  // Lisp 系
  '.scm': 'scheme',
  '.ss': 'scheme',
  '.rkt': 'scheme',
  '.lisp': 'lisp',
  '.cl': 'lisp',
  '.el': 'lisp',
  '.fnl': 'fennel',
  // 其它前端/工具
  '.elm': 'elm',
  '.purs': 'purescript',
  '.re': 'reason',
  '.rei': 'reason',
  '.hx': 'haxe',
  '.gd': 'gdscript',
  // HTTP / 文档
  '.http': 'plaintext',
  '.rest': 'plaintext',
  '.rst': 'restructuredtext',
  '.adoc': 'asciidoc',
  '.asciidoc': 'asciidoc',
  // 其它文本
  '.vim': 'vim',
  '.diff': 'diff',
  '.patch': 'diff',
  '.log': 'log',
  '.txt': 'plaintext',
  '.text': 'plaintext',
  '.tsv': 'plaintext',
  '.env': 'plaintext',
  '.gitignore': 'plaintext',
  '.gitattributes': 'plaintext',
  '.dockerignore': 'plaintext',
  '.qml': 'javascript',
  '.qbs': 'javascript',
  '.jenkinsfile': 'groovy',
  '.avsc': 'json',
  '.nut': 'plaintext',
  '.tscn': 'plaintext',
  '.tres': 'plaintext',
  '.abap': 'plaintext',
  '.cairo': 'plaintext'
}
